### ISSUE TITLE
Move to a Julia org

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/SparseDiffTools.jl#3]
We should make sure this moves to a Julia org so it can get routine maintenance by many individuals. I would be fine with it in JuliaDiffEq but it may find a better home in JuliaDiff (if that's still a thing?). I can take one of the admin spots and will commit to maintenance for whatever future.

**Comment by pkj-m** [comment]
Hi. I've added you as a collaborator for this repository. Is that sufficient to move the repo under JuliaDiffEq?

**Comment by matbesancon** [comment]
Note: decided to do this later, Travis will be faster outside JuliaDiffEq

**Comment by matbesancon** [comment]
Can be closed

**Comment by ChrisRackauckas** [comment]
You should have maintenance privileges as well once you accept the invite.
