### ISSUE TITLE
First pass

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/SparseDiffTools.jl#4]
- [x] Convert sparse matrix to graph
- [x] Perform coloring on graph
- [x] spit out color vector
- [x] make finite differencing choose directions based on color vector
- [x] add the Jacobian decompression
- [x] make dual numbers in the directions of the color vector
- [x] decompress the partials into the Jacobian

**Comment by pkj-m** [comment]
https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/pull/58 handles finite differencing based on color vector and Jacobian decompression.

**Comment by ChrisRackauckas** [comment]
Now this is how you do forward-mode automatic differentiation in the direction of v: https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/src/jacvec_operators.jl#L7-L13 . Let me know if you'd like some starter code for this, or want to discuss how that's working. Essentially what needs to be done is a multi-dimensional partial in the direction of each color vector, so `color .== i` for each `i < maximum(color)`, making one dual `cache1 .= ForwardDiff.Dual{JacVecTag}.(x, v1, v2, v3, .., vn)`, solving with that dual, and extracting each vector.

For a first pass let it be allocating, and then we'll optimize it in the next step.

**Comment by ChrisRackauckas** [comment]
@pkj-m nicely done!

**Comment by pkj-m** [comment]
For record, #17 introduces dual numbers in the direction determined by the coloring vector.
