### ISSUE TITLE
Get rid of Int64 

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/SparseDiffTools.jl#53]
There are a lot of `Int64` floating around in the code. I suggest replacing all of them with `Int`.

**Comment by devmotion** [comment]
Probably due to the unneeded `Int64` mixed with `Int`, SparseDiffTools does not even compile on Win32: https://ci.appveyor.com/project/devmotion/sparsedifftools-jl/build/job/iix18ehavbhsemv1

**Comment by devmotion** [comment]
@ChrisRackauckas Maybe that's one reason why the compilation times are severely more broken on Win32. In general, the compilation times of SparseDiffTools are quite large and in similar ranges (around 2-3 minutes on 64bit) as the additional compilation time observed in OrdinaryDiffEq and StochasticDiffEq, even on my branch with Cassette being removed: https://travis-ci.com/JuliaDiffEq/SparseDiffTools.jl/builds/119856871 and https://ci.appveyor.com/project/devmotion/sparsedifftools-jl/build/job/p813quukxxoea3w0. Additionally, the test on Win64 produces an `EXCEPTION_ACCESS_VIOLATION`.

**Comment by ChrisRackauckas** [comment]
Yes, that's really really bad. I'll just fix the Int64s and release...

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/SparseDiffTools.jl/commit/f878a188cefcb95d1196c530369ed35d9a6f5158 no more of this lol
