### ISSUE TITLE
Value type

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/SparseDiffTools.jl#54]
It seems, the function in lines https://github.com/JuliaDiffEq/SparseDiffTools.jl/blob/master/src/differentiation/compute_jacobian_ad.jl#L10-L16 is equivalent to the bad example in https://docs.julialang.org/en/v1/manual/performance-tips/index.html#Types-with-values-as-parameters-1? Should it just be `chunksize = max(maximum(colors), DEFAULT_CHUNK_SIZE)` in https://github.com/JuliaDiffEq/SparseDiffTools.jl/blob/master/src/differentiation/compute_jacobian_ad.jl#L27 instead? Or could the `Val` instance still be helpful when calling `generate_chunked_partials`?

But then still the same problem appears in https://github.com/JuliaDiffEq/SparseDiffTools.jl/blob/master/src/differentiation/compute_jacobian_ad.jl#L46?

**Comment by ChrisRackauckas** [comment]
The user is supposed to pass a value type. The partials have to be known at compile time for the tuple length.

**Comment by ChrisRackauckas** [comment]
If all we have is the length, we determine it at cache construction time so the type is gotten once, and then further function calls have it all inferred. It's the same in ForwardDiff and not the bad example there.

**Comment by devmotion** [comment]
I'm just desperately trying to find all possible issues and was confused by the `default_chunk_size` function and the fact that integers are "converted" to `Val`s. But then this is probably not a major issue, it seems.
