### ISSUE TITLE
Julia 1.0

### ISSUE THREAD

**Issue by matthieugomez** [JuliaDiffEq/SparseDiffTools.jl#70]
Project.toml allows Julia 1.0 but, with this version, the package returns an error 
`eachrow not defined`

**Comment by ChrisRackauckas** [comment]
I think this might be fixed just by adding `using Compat`? I have no plans to spend a bunch of time on Julia v1.0 since it's soon going to be deprecated, but if that's all it needs then that's a quick fix.

**Comment by matbesancon** [comment]
that or
julia = "≥ 1.1" on the Project.toml

**Comment by ChrisRackauckas** [comment]
That blocked things in weird ways though because of silly package manager issues, so it was easier to just keep things open as it was less breaking.
